# Server settings ：后面必须有空格
server:
    port: 9999
    address: localhost
# SPRING PROFILES
spring:     
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&amp;characterEncoding=utf-8&amp;useSSL=false
        username: root
        password: liusu9686
    # HTTP ENCODING
    http:
        encoding.charset: UTF-8
        encoding.enabled: true
        encoding.force: true
    devtools:
        restart:
          enabled: true
    mail:
      host: smtp.qq.com
      username: 1255769116@qq.com
      password: gvgjhndrzzalbafc
      protocol: smtp
      port: 25
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
              required: true
# MyBatis
mybatis:
    mapper-locations: classpath:/mapper/*.xml
    type-aliases-package: com.lotus.model
    #typeAliasesPackage: com.lotus.model
    #mapperLocations: classpath:/com/lotus/mapper/*.xml
    configLocation: classpath:/mybatis-config.xml

# LOGGING
logging:
    level:
       com.lotus.dao: INFO,DEBUG